server:
  port: 8443
  max_connections: 100
  log_level: info

logging:
  file: emme.log
  level: debug
  format: plain         # or "json"
  buffer_size: 16384
  rollover_size: 10485760   # 10 MB
  rollover_daily: true
  appender_flags:
    - file
    - console  

ssl:
  certificate: "certs/dev.crt"
  private_key: "certs/dev.key"

routes:
    - path: "/static/"
      technology: "static"
      document_root: "/var/www/html"
    - path: "/api/"
      technology: "reverse_proxy"
      backend: "127.0.0.1:8081"
