#ifndef HTTP_STATUS_H
#define HTTP_STATUS_H

#define HTTP_STATUS_CONTINUE            100
#define HTTP_STATUS_SWITCHING_PROTOCOLS 101

#define HTTP_STATUS_OK                  200
#define HTTP_STATUS_CREATED             201
#define HTTP_STATUS_NO_CONTENT          204

#define HTTP_STATUS_MOVED_PERMANENTLY   301
#define HTTP_STATUS_FOUND               302
#define HTTP_STATUS_NOT_MODIFIED        304

#define HTTP_STATUS_BAD_REQUEST         400
#define HTTP_STATUS_UNAUTHORIZED        401
#define HTTP_STATUS_FORBIDDEN           403
#define HTTP_STATUS_NOT_FOUND           404
#define HTTP_STATUS_METHOD_NOT_ALLOWED  405
#define HTTP_STATUS_PAYLOAD_TOO_LARGE   413

#define HTTP_STATUS_INTERNAL_ERROR      500
#define HTTP_STATUS_NOT_IMPLEMENTED     501
#define HTTP_STATUS_BAD_GATEWAY         502
#define HTTP_STATUS_SERVICE_UNAVAILABLE 503
#define HTTP_STATUS_GATEWAY_TIMEOUT     504

#define HTTP_STATUS_SUCCESS_MIN         200
#define HTTP_STATUS_SUCCESS_MAX         299
#define HTTP_STATUS_REDIRECT_MIN        300
#define HTTP_STATUS_REDIRECT_MAX        399
#define HTTP_STATUS_CLIENT_ERROR_MIN    400
#define HTTP_STATUS_CLIENT_ERROR_MAX    499
#define HTTP_STATUS_SERVER_ERROR_MIN    500
#define HTTP_STATUS_SERVER_ERROR_MAX    599

#endif // HTTP_STATUS_H
