name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          # first axis: Ubuntu runner, no container
          - os-name: ubuntu
            runs-on: ubuntu-latest
            container: "" 
            install-deps: |
              sudo apt-get update
              sudo apt-get install -y build-essential liburing-dev libssl-dev libyaml-dev libnghttp2-dev criterion-dev
          # second axis: Fedora container on Ubuntu runner
          - os-name: fedora
            runs-on: ubuntu-latest
            container: fedora:latest
            install-deps: |
              sudo dnf -y update
              sudo dnf -y install @development-tools \
                liburing-devel openssl-devel libyaml-devel nghttp2-devel criterion-devel

    name: Build & Test on ${{ matrix.os-name }}
    runs-on: ${{ matrix.runs-on }}
    # only inject container if non-empty
    container: ${{ matrix.container }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (${{ matrix.os-name }})
        run: |
          # Fedora container already runs as root, so sudo is optional
          ${{ matrix.install-deps }}

      - name: Compile project
        run: make

      - name: Run tests
        run: make test

